import { buildVariantsCss } from "./buildVariants.ts";
import { emitCalcCSS, isCalcNode } from "./calc.ts";
import type { PropertyType, SectionedTokens, Theme } from "./types.ts";
import { boxIn, justify } from "@bearmetal/miscellanea/string";

const OPEN_COMMENT = "/* ";
const CLOSE_COMMENT = " */";

function generatedFileDisclaimer() {
	return `/*\n${
		boxIn(justify([
			"Generated by BearMetal Drip",
			"-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-",
			"DO NOT edit this file manually.",
			"This file is generated automatically from theme files.",
			"To make changes, edit the theme files and run the generator again.",
			"",
			"Read more at https://bear-metal.dev/drip/docs",
		].join("\n")))
	} */\n`;
}

export function cssFromJson(
	theme: Theme,
	scope: string = ":root",
	fullFat: boolean = true,
) {
	const kvs: SectionedTokens = [];
	for (const [key, value] of Object.entries(theme)) {
		if (key.startsWith("#")) continue;
		kvs.push(
			"#region " + key.toUpperCase() + " tokens",
			...constructTokens(value as Theme, getSyntaxByName(key), `--${key}-`),
			"#endregion",
		);
	}
	const properties = fullFat
		? kvs.filter((pair): pair is [string, string, PropertyType] =>
			typeof pair === "object" && !pair[1].startsWith("$") && !pair[1].startsWith("calc(")
		).map(([key, value, syntax]) =>
			[
				`@property ${key} {`,
				`	syntax: "${syntax}";`,
				"	inherits: true;",
				`	initial-value: ${value.replace(/__/g, ".").trim()};`,
				`}`,
			].join("\n")
		).join("\n")
		: [];

	return [
		generatedFileDisclaimer(),
		...(fullFat ? ["/* #region Custom Properties */", properties, "/* #endregion */", ""] : []),
		`${scope} {`,
		kvs.map((pair) => {
			if (!pair) return "";
			if (typeof pair === "string") {
				return `\n${OPEN_COMMENT}${
					pair.startsWith("#") ? pair : "\n" + boxIn(pair)
				}${CLOSE_COMMENT}`;
			}
			return `\t${pair[0]}: ${
				pair[1].startsWith("$")
					? `var(${pair[1].replace("$", "").replace(/__/g, ".").trim()})`
					: pair[1].replace(/__/g, ".").trim()
			};`;
		}).join("\n"),
		"\n}\n",
		fullFat ? buildVariantsCss(theme) : "",
	].join("\n");
}

/** Lightweight CSS for runtime injection - no disclaimer, no @property, variants scoped to selector. */
export function themeCSS(theme: Theme, selector: string): string {
	const kvs: SectionedTokens = [];
	for (const [key, value] of Object.entries(theme)) {
		if (key.startsWith("#")) continue;
		kvs.push(...constructTokens(value as Theme, getSyntaxByName(key), `--${key}-`));
	}
	const props = kvs
		.filter((pair): pair is [string, string, PropertyType] => typeof pair === "object")
		.map(([key, value]) =>
			`\t${key}: ${
				value.startsWith("$")
					? `var(${value.replace("$", "").replace(/__/g, ".").trim()})`
					: value.replace(/__/g, ".").trim()
			};`
		)
		.join("\n");
	const varBlock = `${selector} {\n${props}\n}`;
	const variantBlock = buildVariantsCss(theme, selector);
	return [varBlock, variantBlock].filter(Boolean).join("\n\n");
}

const skipKeys = ["$calc"];

function constructTokens<T extends Theme>(
	theme: T,
	syntax: PropertyType,
	prefix: string = "--",
	path: string[] = [],
	depth: number = 0,
): SectionedTokens {
	const kvs: SectionedTokens = [];
	if (prefix.startsWith("--color")) {
		if (depth === 1 && path.at(-1) !== "bearmetal") {
			kvs.push(`${prefix.toUpperCase().replaceAll("-", " ").trim()}: ${path.at(-1)}`);
		}
		if (depth === 2 && path.at(-2) === "bearmetal") {
			kvs.push(
				`BearMetal ${prefix.toUpperCase().replaceAll("-", " ").trim()}: ${path.at(-1)}`.replace(
					/: $/,
					"",
				),
			);
		}
	}
	if (Object.keys(theme).some((k) => !isNaN(Number(k))) && path.at(-1)) {
		kvs.push("");
	}

	for (const [key, value] of Object.entries(theme)) {
		if (skipKeys.includes(key)) continue;
		if (isCalcNode(value)) {
			kvs.push([
				prefix + path.concat([key]).filter(Boolean).join("-"),
				emitCalcCSS(value),
				syntax,
			]);
		}
		if (typeof value === "string") {
			kvs.push([
				prefix + path.concat([key.replace("$ref", "")]).filter(Boolean).join("-"),
				value.replace("$", "$--").replaceAll(".", "-").replace(/__/g, "."),
				syntax,
			]);
		} else if (!Array.isArray(value)) {
			kvs.push(...constructTokens(value as Theme, syntax, prefix, [...path, key], depth + 1));
		}
	}

	return kvs;
}

function getSyntaxByName(name: string): PropertyType {
	const p: Record<string, PropertyType> = {
		color: "<color>",
		"*": "<*>",
	};
	return p[name as keyof typeof p] ?? "<*>";
}
