/**
 * @module
 * Type-checked icon names for an SVG sprite sheet.
 *
 * An `<bm-icon icon="...">` names a `<symbol id>` in a sheet, and a typo renders nothing. This
 * reads the symbol ids out of one or more sheets and writes them as a string-literal union, so
 * `<Icon name>` can be checked against the set the app actually ships — regenerated from the sheet
 * rather than committed by hand.
 *
 * ```sh
 * deno run -R -W jsr:@bearmetal/drip/icons public/iconography/*.svg --out=gen/icons.ts --name=TablerIcon
 * ```
 *
 * ```ts
 * import { writeIconTypes } from "@bearmetal/drip/icons";
 * await writeIconTypes(["public/iconography/base.svg"], "gen/icons.ts", { name: "TablerIcon" });
 * ```
 */

const SYMBOL_ID = /<symbol\b[^>]*?\sid\s*=\s*(["'])([^"']+)\1/g;

/** Every `<symbol>` id in an SVG sprite sheet, sorted and de-duplicated. */
export function iconNames(svg: string): string[] {
	const names = new Set<string>();
	for (const m of svg.matchAll(SYMBOL_ID)) names.add(m[2]);
	return [...names].sort();
}

/** Options for {@linkcode iconTypes} and {@linkcode writeIconTypes}. */
export interface IconTypesOptions {
	/** Name of the exported union type. Defaults to `IconName`. */
	name?: string;
	/** Also export the names as a `const` array named `<name>s` (e.g. `IconNames`). */
	list?: boolean;
}

/** TypeScript source declaring `names` as a string-literal union. */
export function iconTypes(names: Iterable<string>, options: IconTypesOptions = {}): string {
	const { name = "IconName", list = false } = options;
	if (!/^[A-Za-z_$][\w$]*$/.test(name)) throw new TypeError(`"${name}" is not a type name`);
	const sorted = [...new Set(names)].sort();
	const header = "// Generated by @bearmetal/drip/icons from the icon sheet. Do not edit.\n\n";
	const union = sorted.length
		? sorted.map((n) => `\t| ${JSON.stringify(n)}`).join("\n")
		: "\tnever";
	let out = `${header}export type ${name} =\n${union};\n`;
	if (list) {
		out += `\nexport const ${name}s: readonly ${name}[] = ${JSON.stringify(sorted, null, "\t")};\n`;
	}
	return out;
}

/**
 * Reads `sheets`, merges their symbol ids, and writes the union to `out`. The file is only
 * rewritten when its content would change, so a `--watch` process isn't restarted for nothing.
 * Returns the names written.
 */
export async function writeIconTypes(
	sheets: (string | URL)[],
	out: string | URL,
	options: IconTypesOptions = {},
): Promise<string[]> {
	const names = new Set<string>();
	for (const sheet of sheets) {
		for (const name of iconNames(await Deno.readTextFile(sheet))) names.add(name);
	}
	const source = iconTypes(names, options);
	const existing = await Deno.readTextFile(out).catch(() => undefined);
	if (existing !== source) {
		const path = out instanceof URL ? out.pathname : out;
		const dir = path.replace(/[\\/][^\\/]*$/, "");
		if (dir && dir !== path) await Deno.mkdir(dir, { recursive: true });
		await Deno.writeTextFile(out, source);
	}
	return [...names].sort();
}

if (import.meta.main) {
	const sheets: string[] = [];
	let out: string | undefined;
	const options: IconTypesOptions = {};
	for (const arg of Deno.args) {
		if (arg.startsWith("--out=")) out = arg.slice(6);
		else if (arg.startsWith("--name=")) options.name = arg.slice(7);
		else if (arg === "--list") options.list = true;
		else sheets.push(arg);
	}
	if (!sheets.length) {
		console.error("usage: icons <sheet.svg...> [--out=icons.ts] [--name=IconName] [--list]");
		Deno.exit(1);
	}
	if (out) {
		const names = await writeIconTypes(sheets, out, options);
		console.log(`${names.length} icon names → ${out}`);
	} else {
		const names = new Set<string>();
		for (const sheet of sheets) {
			for (const name of iconNames(await Deno.readTextFile(sheet))) names.add(name);
		}
		console.log(iconTypes(names, options));
	}
}
