import { buildVariantsCss } from "./buildVariants.ts";
import { emitCalcCSS, isCalcNode } from "./calc.ts";
import type { CalcNode, CalcRoot, PropertyType, SectionedTokens, Theme } from "./types.ts";

const OPEN_COMMENT = "/* ";
const CLOSE_COMMENT = " */";
const SEPARATOR = "═";
const TOPL = "╔";
const TOPR = "╗";
const BOTL = "╚";
const BOTR = "╝";
const SIDE = "║";

function boxIn(content: string) {
	const length = content.split("\n").reduce((acc, line) => Math.max(acc, line.length), 0);
	const padding = 1;
	const separator = "".padEnd(
		length + padding * 2,
		SEPARATOR,
	);

	return `${TOPL}${separator}${TOPR}\n${
		content.replace(/^/gm, `${SIDE} `).replace(/$/gm, ` ${SIDE}`)
	}\n${BOTL}${separator}${BOTR}`;
}
function justify(s: string) {
	const length = s.split("\n").reduce((acc, line) => Math.max(acc, line.length), 0);
	return s.split("\n").map((line) => line.padEnd(length)).join("\n");
}

function generatedFileDisclaimer() {
	return `/*\n${
		boxIn(justify([
			"Generated by BearMetal Drip",
			"-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-",
			"DO NOT edit this file manually.",
			"This file is generated automatically from theme files.",
			"To make changes, edit the theme files and run the generator again.",
			"",
			"Read more at https://bear-metal.dev/drip/docs",
		].join("\n")))
	} */\n`;
}

function cssFromJson(
	theme: Theme,
	scope: string = ":root",
	fullFat: boolean = true,
) {
	const kvs: SectionedTokens = [];
	for (const [key, value] of Object.entries(theme)) {
		if (key.startsWith("#")) continue;
		kvs.push(
			"#region " + key.toUpperCase() + " tokens",
			...constructTokens(value as Theme, getSyntaxByName(key), `--${key}-`),
			"#endregion",
		);
	}
	const properties = fullFat
		? kvs.filter((pair): pair is [string, string, PropertyType] =>
			typeof pair === "object" && !pair[1].startsWith("$") && !pair[1].startsWith("calc(")
		).map(([key, value, syntax]) =>
			[
				`@property ${key} {`,
				`	syntax: "${syntax}";`,
				"	inherits: true;",
				`	initial-value: ${value.replace(/__/g, ".").trim()};`,
				`}`,
			].join("\n")
		).join("\n")
		: [];

	const css = [
		generatedFileDisclaimer(),
		...(fullFat ? ["/* #region Custom Properties */", properties, "/* #endregion */", ""] : []),
		`${scope} {`,
		kvs.map((pair) => {
			if (!pair) return "";
			if (typeof pair === "string") {
				return `\n${OPEN_COMMENT}${
					pair.startsWith("#") ? pair : "\n" + boxIn(pair)
				}${CLOSE_COMMENT}`;
			}
			return `\t${pair[0]}: ${
				pair[1].startsWith("$")
					? `var(${pair[1].replace("$", "").replace(/__/g, ".").trim()})`
					: pair[1].replace(/__/g, ".").trim()
			};`;
		}).join("\n"),
		"\n}\n",

		fullFat ? buildVariantsCss(theme) : "",
	].join("\n");
	return css;
}

const skipKeys = ["$calc"];
function constructTokens<
	T extends Theme,
>(
	theme: T,
	syntax: PropertyType,
	prefix: string = "--",
	path: string[] = [],
	depth: number = 0,
): SectionedTokens {
	const kvs: SectionedTokens = [];
	if (prefix.startsWith("--color")) {
		if (depth === 1 && path.at(-1) !== "bearmetal") {
			kvs.push(`${prefix.toUpperCase().replaceAll("-", " ").trim()}: ${path.at(-1)}`);
		}
		if (depth === 2 && path.at(-2) === "bearmetal") {
			kvs.push(
				`BearMetal ${prefix.toUpperCase().replaceAll("-", " ").trim()}: ${path.at(-1)}`.replace(
					/: $/,
					"",
				),
			);
		}
	}
	if (Object.keys(theme).some((k) => !isNaN(Number(k))) && path.at(-1)) {
		kvs.push("");
	}

	for (const [key, value] of Object.entries(theme)) {
		if (skipKeys.includes(key)) continue;
		if (isCalcNode(value)) {
			kvs.push([
				prefix + path.concat([key]).filter(Boolean).join("-"),
				emitCalcCSS(value),
				syntax,
			]);
		}
		if (typeof value === "string") {
			kvs.push([
				prefix + path.concat([key.replace("$ref", "")]).filter(Boolean).join("-"),
				value.replace("$", "$--").replaceAll(".", "-").replace(/__/g, "."),
				syntax,
			]);
		} else if (!Array.isArray(value)) {
			kvs.push(...constructTokens(value as Theme, syntax, prefix, [...path, key], depth + 1));
		}
	}

	return kvs;
}

function getSyntaxByName(name: string): PropertyType {
	const p: Record<string, PropertyType> = {
		color: "<color>",
		"*": "<*>",
	};
	return p[name as keyof typeof p] ?? "<*>";
}

if (import.meta.main) {
	const theme = Deno.args.find((e) => e.startsWith("--theme"))?.split("=")[1] ?? "bearmetal";
	const url = new URL(`./themes/${theme}.theme.json`, import.meta.url);
	const res = await fetch(url);
	const json = await res.json() as Theme;
	const css = cssFromJson(json);
	Deno.writeTextFile(".bearmetal/themes/base.css", css, { create: true });
}
