/**
 * Regenerates the embedded templates from the example apps.
 *
 * `deno task bm:templates`, from the `stack/` directory.
 *
 * Each template is a directory under `../examples/`, and its files are embedded
 * verbatim into `./embedded.ts`. Embedding rather than fetching a tarball at run
 * time means `deno create` works offline, cannot pick up a template built for a
 * different version of the stack, and — because the example is a workspace
 * member — the template is type-checked and linted by `workspace:check` like any
 * other code. A template that does not compile stops being publishable instead
 * of becoming somebody's broken first project.
 *
 * @module
 */

import { walkDir } from "@bearmetal/miscellanea/fs";
import { joinPath } from "@bearmetal/miscellanea";
import { directoryOf } from "@bearmetal/miscellanea/path";

/** Template name → the example directory it is built from. */
const templates: Record<string, string> = {
	default: "../examples/project",
};

/**
 * Files the scaffolder writes itself, or that belong to the workspace rather
 * than to a scaffolded app.
 */
const skip = new Set(["deno.json", "deno.lock"]);

const here = directoryOf(new URL(import.meta.url).pathname);

async function collect(dir: string): Promise<Map<string, string>> {
	const root = joinPath(here, dir);
	const files = new Map<string, string>();
	for await (const entry of walkDir(root)) {
		// `stat` rather than `entry.isFile`, because it follows symlinks — the
		// example's `public/` icon is one, pointing at the repo's own copy, and a
		// scaffolded app needs the file it names rather than a dangling link.
		if (!(await Deno.stat(entry.path)).isFile) continue;
		const relative = entry.path.slice(root.length).replace(/^\//, "");
		if (skip.has(relative)) continue;
		files.set(relative, await Deno.readTextFile(entry.path));
	}
	return new Map([...files].sort(([a], [b]) => a.localeCompare(b)));
}

/** Quotes a file's contents as a template literal, escaping what would end it. */
function quote(text: string): string {
	return "`" + text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";
}

const parts: string[] = [
	"// Generated by `deno task bm:templates`. Do not edit by hand — edit the",
	"// example app the template is built from and regenerate.",
	"",
	"/** Every scaffoldable template, as a map of relative path to file contents. */",
	"export const templates: Record<string, Record<string, string>> = {",
];

for (const [name, dir] of Object.entries(templates)) {
	const files = await collect(dir);
	parts.push(`\t${JSON.stringify(name)}: {`);
	for (const [path, contents] of files) {
		parts.push(`\t\t${JSON.stringify(path)}: ${quote(contents)},`);
	}
	parts.push("\t},");
	console.log(`  ${name}: ${files.size} files from ${dir}`);
}

parts.push("};", "");

await Deno.writeTextFile(joinPath(here, "embedded.ts"), parts.join("\n"));
console.log("wrote templates/embedded.ts");
