/**
 * Regenerates `embedded.ts` from the `woff2` assets named in
 * {@linkcode ./manifest.ts | fontManifest}, inlining each face as a
 * `data:` URI so the sheets ship with the package on JSR with no file reads at
 * runtime.
 *
 * Run with `deno task bm:fonts` from `drip/`.
 *
 * @module
 */

import { fontManifest } from "./manifest.ts";

const HERE = new URL(".", import.meta.url);

function toBase64(bytes: Uint8Array): string {
	let binary = "";
	const chunk = 0x8000;
	for (let i = 0; i < bytes.length; i += chunk) {
		binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
	}
	return btoa(binary);
}

/** The `@font-face` sheet for one manifest entry, faces inlined as `data:` URIs. */
async function sheetFor(key: string): Promise<string> {
	const def = fontManifest[key as keyof typeof fontManifest];
	const rules: string[] = [];
	for (const face of def.faces) {
		const bytes = await Deno.readFile(new URL(`./assets/${face.file}`, HERE));
		const b64 = toBase64(bytes);
		rules.push(
			`@font-face{` +
				`font-family:"${def.family}";` +
				`font-style:${face.style};` +
				`font-weight:${face.weight};` +
				`font-display:swap;` +
				`src:url("data:font/woff2;base64,${b64}") format("woff2")` +
				`}`,
		);
	}
	return rules.join("");
}

async function generate(): Promise<void> {
	const entries: string[] = [];
	let total = 0;
	for (const key of Object.keys(fontManifest)) {
		const sheet = await sheetFor(key);
		total += sheet.length;
		entries.push(`\t${JSON.stringify(key)}: ${JSON.stringify(sheet)},`);
	}

	const out = [
		"// deno-fmt-ignore-file",
		"// AUTO-GENERATED by `deno task bm:fonts` — do not edit.",
		"// Each value is the `@font-face` sheet for one self-hosted family,",
		"// its faces inlined as base64 `data:` URIs. See ./manifest.ts.",
		"",
		'import type { FontKey } from "./manifest.ts";',
		"",
		"/** The `@font-face` sheet for each self-hosted family, keyed as in the manifest. */",
		"export const fontFaces: Record<FontKey, string> = {",
		...entries,
		"};",
		"",
	].join("\n");

	await Deno.writeTextFile(new URL("./embedded.ts", HERE), out);
	console.log(
		`Drip: embedded ${Object.keys(fontManifest).length} font sheet(s), ${
			(total / 1024).toFixed(1)
		} KiB of CSS.`,
	);
}

if (import.meta.main) await generate();
