/**
 * Regenerates `embedded.ts` from the `woff2` assets named in
 * {@linkcode ./manifest.ts | fontManifest}, base64-encoding each face so the
 * fonts ship with the package on JSR with no file reads at runtime. `mod.ts`
 * builds the `@font-face` sheets from them, inlined or linked.
 *
 * Run with `deno task bm:fonts` from `drip/`.
 *
 * @module
 */

import { fontManifest } from "./manifest.ts";

const HERE = new URL(".", import.meta.url);

function toBase64(bytes: Uint8Array): string {
	let binary = "";
	const chunk = 0x8000;
	for (let i = 0; i < bytes.length; i += chunk) {
		binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
	}
	return btoa(binary);
}

async function generate(): Promise<void> {
	const entries: string[] = [];
	let total = 0;
	for (const def of Object.values(fontManifest)) {
		for (const face of def.faces) {
			const bytes = await Deno.readFile(new URL(`./assets/${face.file}`, HERE));
			const b64 = toBase64(bytes);
			total += b64.length;
			entries.push(`\t${JSON.stringify(face.file)}: ${JSON.stringify(b64)},`);
		}
	}

	const out = [
		"// deno-fmt-ignore-file",
		"// AUTO-GENERATED by `deno task bm:fonts` — do not edit.",
		"// Each value is one self-hosted face's woff2, base64-encoded, keyed by its",
		"// manifest `file`. See ./manifest.ts.",
		"",
		"/** Base64 `woff2` bytes for every face in the manifest, keyed by its `file`. */",
		"export const fontData: Record<string, string> = {",
		...entries,
		"};",
		"",
	].join("\n");

	await Deno.writeTextFile(new URL("./embedded.ts", HERE), out);
	console.log(
		`Drip: embedded ${entries.length} font face(s), ${(total / 1024).toFixed(1)} KiB of base64.`,
	);
}

if (import.meta.main) await generate();
