/**
 * Regenerates `embedded.ts` from the compliant stylesheets (`base.css`,
 * `components.css`, `animations.css`), so they ship with the package as
 * strings. A published package is fetched over HTTP and a browser bundle has
 * no sibling files to read, so the `.css` files are the source and this module
 * is how everything else reaches them.
 *
 * Run with `deno task bm:css` from `drip/`.
 *
 * @module
 */

export const COMPLIANT_SOURCES = {
	base: "base.css",
	components: "components.css",
	animations: "animations.css",
} as const;

const HERE = new URL(".", import.meta.url);

/** The source of `embedded.ts` for the current contents of the `.css` files. */
export async function renderEmbedded(): Promise<string> {
	const entries: string[] = [];
	for (const [id, file] of Object.entries(COMPLIANT_SOURCES)) {
		const css = await Deno.readTextFile(new URL(`./${file}`, HERE));
		entries.push(`\t${id}: ${JSON.stringify(css)},`);
	}
	return [
		"// deno-fmt-ignore-file",
		"// AUTO-GENERATED by `deno task bm:css` — do not edit. Edit the .css files beside it.",
		"",
		'import type { CompliantID } from "./compliantCSS.ts";',
		"",
		"/** Each compliant stylesheet, keyed by its id. */",
		"export const compliantSheets: Record<CompliantID, string> = {",
		...entries,
		"};",
		"",
	].join("\n");
}

if (import.meta.main) {
	await Deno.writeTextFile(new URL("./embedded.ts", HERE), await renderEmbedded());
	console.log("Drip: embedded the compliant stylesheets.");
}
