import { isDev } from "@bearmetal/miscellanea/environment";
import { buildVariantsCss, getThemeVariants, variantDefinedProperties } from "./variants.ts";
import { emitCalcCSS, isCalcNode } from "./calc.ts";
import { reportDiagnostics, validateVariants } from "./validate.ts";
import type { PropertyType, SectionedTokens, Theme } from "../types.ts";
import { boxIn, justify } from "@bearmetal/miscellanea/string";

const OPEN_COMMENT = "/* ";
const CLOSE_COMMENT = " */";

/** Top-level theme keys that hold metadata rather than tokens. */
const META_KEYS = ["variants"];

function generatedFileDisclaimer() {
	if (isDev()) return "";
	return `/*\n${
		boxIn(justify([
			"Generated by BearMetal Drip",
			"-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-",
			"DO NOT edit this file manually.",
			"This file is generated automatically from theme files.",
			"To make changes, edit the theme files and run the generator again.",
			"",
			"Read more at https://bear-metal.dev/drip/docs",
		].join("\n")))
	} */\n`;
}

/** Options for {@linkcode cssFromJson}. */
export interface CssFromJsonOptions {
	/** Selector the token block hangs off. Defaults to `:root`. */
	scope?: string;
	/** Emit `@property` registrations and the file disclaimer. Defaults to `true`. */
	fullFat?: boolean;
	/** Name used in diagnostics. Defaults to `"theme"`. */
	name?: string;
	/**
	 * Run generate-time validation (media queries, dangling `var()` references).
	 * Defaults to `true`.
	 */
	validate?: boolean;
}

/**
 * Renders a theme to a stylesheet: `@property` registrations, the token block,
 * and one block per variant.
 *
 * Output is one declaration per line. The file is generated, so there is
 * nothing to gain from packing it onto one line and plenty to lose — a
 * 15,000-character line is unreviewable in a diff and makes every
 * line-oriented tool give the wrong answer about it.
 */
export function cssFromJson(
	theme: Theme,
	scopeOrOptions: string | CssFromJsonOptions = ":root",
	fullFatArg: boolean = true,
): string {
	const options: CssFromJsonOptions = typeof scopeOrOptions === "string"
		? { scope: scopeOrOptions, fullFat: fullFatArg }
		: scopeOrOptions;
	const scope = options.scope ?? ":root";
	const fullFat = options.fullFat ?? true;
	const joiner = "\n";

	const kvs = collectThemeTokens(theme);

	if (options.validate !== false) {
		reportDiagnostics(
			validateVariants(getThemeVariants(theme), definedProperties(theme, kvs)),
			options.name ?? "theme",
		);
	}

	const properties = fullFat
		? kvs.filter((pair): pair is [string, string, PropertyType] =>
			typeof pair === "object" && !pair[1].startsWith("$") && !pair[1].startsWith("calc(")
		).map(([key, value, syntax]) =>
			[
				`@property ${key} {`,
				`	syntax: "${syntax}";`,
				"	inherits: true;",
				`	initial-value: ${value.replace(/__/g, ".").trim()};`,
				`}`,
			].join(joiner)
		).join(joiner)
		: [];

	return [
		generatedFileDisclaimer(),
		...(fullFat ? ["/* #region Custom Properties */", properties, "/* #endregion */", ""] : []),
		`${scope} {`,
		kvs.map((pair) => {
			if (!pair) return "";
			if (typeof pair === "string") {
				return `\n${OPEN_COMMENT}${
					pair.startsWith("#") ? pair : "\n" + boxIn(pair)
				}${CLOSE_COMMENT}`;
			}
			return `\t${pair[0]}: ${emitValue(pair[1])};`;
		}).join(joiner),
		`${joiner}}${joiner}`,
		fullFat ? buildVariantsCss(theme, { selector: scope, joiner }) : "",
	].join(joiner);
}

/**
 * Lightweight CSS for runtime injection — no disclaimer, no `@property`,
 * variants scoped to the given selector.
 */
export function themeCSS(theme: Theme, selector: string): string {
	const joiner = "\n";
	const props = collectThemeTokens(theme)
		.filter((pair): pair is [string, string, PropertyType] => typeof pair === "object")
		.map(([key, value]) => `\t${key}: ${emitValue(value)};`)
		.join(joiner);

	const varBlock = `${selector} {${joiner}${props}${joiner}}`;
	const variantBlock = buildVariantsCss(theme, { selector, joiner });
	return [varBlock, variantBlock].filter(Boolean).join("\n\n");
}

function emitValue(value: string): string {
	return value.startsWith("$")
		? `var(${value.replace("$", "").replace(/__/g, ".").trim()})`
		: value.replace(/__/g, ".").trim();
}

/** Walks every namespace in a theme and flattens it into emit-ready tokens. */
function collectThemeTokens(theme: Theme): SectionedTokens {
	const kvs: SectionedTokens = [];
	for (const [key, value] of Object.entries(theme)) {
		if (key.startsWith("#") || META_KEYS.includes(key)) continue;
		kvs.push(
			"#region " + key.toUpperCase() + " tokens",
			...constructTokens(value as Theme, getSyntaxByName(key), `--${key}-`),
			"#endregion",
		);
	}
	return kvs;
}

/**
 * Every custom property the generated stylesheet defines — the flattened token
 * tree plus whatever the variant blocks introduce.
 */
function definedProperties(theme: Theme, kvs: SectionedTokens): Set<string> {
	const defined = variantDefinedProperties(theme);
	for (const pair of kvs) {
		if (typeof pair === "object" && pair) defined.add(pair[0]);
	}
	return defined;
}

const skipKeys = ["$calc"];

/**
 * A colour ramp stores its seed under an empty key (legacy) or `base`. `base`
 * only means "the seed" among numeric stops, so a token genuinely named `base`
 * elsewhere in the tree keeps its own name.
 */
function isRamp(node: Theme): boolean {
	return Object.keys(node).some((k) => k !== "" && !isNaN(Number(k)));
}

function constructTokens<T extends Theme>(
	theme: T,
	syntax: PropertyType,
	prefix: string = "--",
	path: string[] = [],
	depth: number = 0,
): SectionedTokens {
	const kvs: SectionedTokens = [];
	if (prefix.startsWith("--color")) {
		if (depth === 1 && path.at(-1) !== "bearmetal") {
			kvs.push(`${prefix.toUpperCase().replaceAll("-", " ").trim()}: ${path.at(-1)}`);
		}
		if (depth === 2 && path.at(-2) === "bearmetal") {
			kvs.push(
				`BearMetal ${prefix.toUpperCase().replaceAll("-", " ").trim()}: ${path.at(-1)}`.replace(
					/: $/,
					"",
				),
			);
		}
	}
	const ramp = isRamp(theme);
	if (ramp && path.at(-1)) {
		kvs.push("");
	}

	for (const [key, value] of Object.entries(theme)) {
		if (skipKeys.includes(key)) continue;
		const segment = ramp && key === "base" ? "" : key.replace("$ref", "");
		if (isCalcNode(value)) {
			kvs.push([
				prefix + path.concat([segment]).filter(Boolean).join("-"),
				emitCalcCSS(value),
				syntax,
			]);
		}
		if (typeof value === "string") {
			kvs.push([
				prefix + path.concat([segment]).filter(Boolean).join("-"),
				value.replace("$", "$--").replaceAll(".", "-").replace(/__/g, "."),
				syntax,
			]);
		} else if (!Array.isArray(value)) {
			kvs.push(...constructTokens(value as Theme, syntax, prefix, [...path, key], depth + 1));
		}
	}

	return kvs;
}

function getSyntaxByName(name: string): PropertyType {
	const p: Record<string, PropertyType> = {
		color: "<color>",
		"*": "<*>",
	};
	return p[name as keyof typeof p] ?? "<*>";
}
