import { toPascalCase } from "@bearmetal/miscellanea";
import { walkDir } from "@bearmetal/miscellanea/fs";

function extractIds(svg: string): string[] {
	return [...svg.matchAll(/<symbol id="([^"]+)"/g)].map((m) => m[1]).sort();
}

const [path] = Deno.args;

if (!path) {
	throw "You must provide a path to the directory holding the compiled icon sheets.";
}

const dir = path.replace(/\/+$/, "");
const setName = toPascalCase(dir.split("/").at(-1)!);

const sheets: { sheet: string; ids: string[] }[] = [];
for await (const entry of walkDir(dir)) {
	if (!entry.isFile || !entry.name.endsWith(".svg")) continue;
	const sheet = entry.name.replace(".svg", "");
	const ids = extractIds(await Deno.readTextFile(entry.path));
	if (ids.length) sheets.push({ sheet, ids });
}
sheets.sort((a, b) => a.sheet.localeCompare(b.sheet));

const types = sheets.map(({ sheet, ids }) => {
	// "base" is the combined sheet already carrying every style's disambiguated ids,
	// so it stands in for the icon set's overall union rather than getting its own suffix.
	const name = `${setName}${sheet === "base" ? "" : toPascalCase(sheet)}Icon`;
	return `export type ${name} =\n\t| "${ids.join('"\n\t| "')}";`;
});

await Deno.writeTextFile(
	`${dir}/types.ts`,
	"// Auto-generated by buildIconTypes.ts — do not edit directly.\n\n" + types.join("\n\n") + "\n",
);
